const data = [
  {
    agent_id: 1,
    agent_name: "오채원",
    position: "Forward",
    attack: 95,
    defense: 47,
    speed: 75,
  },

  {
    agent_id: 2,
    agent_name: "허경자",
    position: "Forward",
    attack: 94,
    defense: 35,
    speed: 89,
  },
  {
    agent_id: 3,
    agent_name: "김상훈",
    position: "Forward",
    attack: 100,
    defense: 40,
    speed: 88,
  },
  {
    agent_id: 4,
    agent_name: "안수빈",
    position: "Forward",
    attack: 97,
    defense: 43,
    speed: 94,
  },
  {
    agent_id: 5,
    agent_name: "민동현",
    position: "Forward",
    attack: 93,
    defense: 39,
    speed: 90,
  },

  {
    agent_id: 6,
    agent_name: "이민재",
    position: "Forward",
    attack: 80,
    defense: 34,
    speed: 96,
  },
  {
    agent_id: 7,
    agent_name: "이영수",
    position: "Forward",
    attack: 83,
    defense: 45,
    speed: 77,
  },
  {
    agent_id: 8,
    agent_name: "김민수",
    position: "Forward",
    attack: 87,
    defense: 32,
    speed: 85,
  },
  {
    agent_id: 9,
    agent_name: "한수진",
    position: "Forward",
    attack: 84,
    defense: 40,
    speed: 82,
  },
  {
    agent_id: 10,
    agent_name: "김예은",
    position: "Forward",
    attack: 100,
    defense: 33,
    speed: 92,
  },
  {
    agent_id: 11,
    agent_name: "이정수",
    position: "Midfielder",
    attack: 70,
    defense: 50,
    speed: 71,
  },
  {
    agent_id: 12,
    agent_name: "김영미",
    position: "Midfielder",
    attack: 64,
    defense: 50,
    speed: 71,
  },
  {
    agent_id: 13,
    agent_name: "황하윤",
    position: "Midfielder",
    attack: 63,
    defense: 57,
    speed: 61,
  },
  {
    agent_id: 14,
    agent_name: "김경희",
    position: "Midfielder",
    attack: 61,
    defense: 60,
    speed: 70,
  },
  {
    agent_id: 15,
    agent_name: "한지훈",
    position: "Midfielder",
    attack: 68,
    defense: 55,
    speed: 62,
  },
  {
    agent_id: 16,
    agent_name: "김준혁",
    position: "Midfielder",
    attack: 63,
    defense: 64,
    speed: 65,
  },
  {
    agent_id: 17,
    agent_name: "김지현",
    position: "Midfielder",
    attack: 75,
    defense: 59,
    speed: 78,
  },
  {
    agent_id: 18,
    agent_name: "이종수",
    position: "Midfielder",
    attack: 75,
    defense: 63,
    speed: 78,
  },
  {
    agent_id: 19,
    agent_name: "이지후",
    position: "Midfielder",
    attack: 79,
    defense: 69,
    speed: 60,
  },
  {
    agent_id: 20,
    agent_name: "장지혜",
    position: "Midfielder",
    attack: 64,
    defense: 62,
    speed: 72,
  },
  {
    agent_id: 21,
    agent_name: "송영희",
    position: "Defender",
    attack: 44,
    defense: 95,
    speed: 68,
  },
  {
    agent_id: 22,
    agent_name: "이민석",
    position: "Defender",
    attack: 43,
    defense: 88,
    speed: 60,
  },
  {
    agent_id: 23,
    agent_name: "김순옥",
    position: "Defender",
    attack: 37,
    defense: 91,
    speed: 67,
  },
  {
    agent_id: 24,
    agent_name: "이지우",
    position: "Defender",
    attack: 42,
    defense: 80,
    speed: 53,
  },
  {
    agent_id: 25,
    agent_name: "이준호",
    position: "Defender",
    attack: 42,
    defense: 82,
    speed: 68,
  },
  {
    agent_id: 26,
    agent_name: "김정호",
    position: "Defender",
    attack: 30,
    defense: 96,
    speed: 68,
  },
  {
    agent_id: 27,
    agent_name: "이지호",
    position: "Defender",
    attack: 47,
    defense: 91,
    speed: 64,
  },
  {
    agent_id: 28,
    agent_name: "권경자",
    position: "Defender",
    attack: 49,
    defense: 98,
    speed: 50,
  },
  {
    agent_id: 29,
    agent_name: "김중수",
    position: "Defender",
    attack: 38,
    defense: 85,
    speed: 54,
  },
  {
    agent_id: 30,
    agent_name: "김지원",
    position: "Defender",
    attack: 31,
    defense: 99,
    speed: 66,
  },
];

export default data;
